# © 2011 Steve McCoy. Available under the MIT license.

application: itsapad
version: 2
runtime: go
api_version: go1

handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
- url: /clean
  script: _go_app
  login: admin
- url: /.*
  script: _go_app
