# Copyright © 2011 Steve McCoy
#Licensed under the MIT License. See LICENSE for details.
application: itsapad
version: 1
runtime: go
api_version: 1

handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /.*
  script: _go_app
