# Copyright © 2011 Steve McCoy
#Licensed under the MIT License. See LICENSE for details.
application: itsapad
version: 2
runtime: go
api_version: go1

handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
- url: /.*
  script: _go_app
